# Theoretical Questions:

Q 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans. NumPy (Numerical Python) is a library that adds support for large, multi-dimensional arrays and matrices, along with a wide range of high-performance mathematical functions to operate on them. The purpose of NumPy is to provide a robust and efficient way to perform numerical computations in Python, making it an essential tool for scientific computing and data analysis.

Advantages of NumPy:

1. Speed: NumPy operations are significantly faster than Python's built-in list operations.
2. Efficient memory usage: NumPy arrays require less memory than Python lists.
3. Vectorized operations: NumPy allows for element-wise operations on entire arrays, making it easier to perform complex calculations.
4. Matrix operations: NumPy provides an efficient way to perform matrix multiplications and other linear algebra operations.
5. Interoperability: NumPy arrays can be easily converted to and from other formats, such as Pandas DataFrames.

NumPy enhances Python's capabilities for numerical operations in several ways:

1. Multi-dimensional arrays: NumPy introduces support for multi-dimensional arrays, enabling efficient storage and manipulation of large datasets.
2. Vectorized operations: NumPy's vectorized operations eliminate the need for loops, making code more concise and faster.
3. High-performance functions: NumPy provides optimized implementations of common mathematical functions, such as linear algebra operations, Fourier transforms, and random number generation.
4. Compatibility: NumPy arrays can be used with other popular libraries, such as Pandas, SciPy, and Matplotlib, making it a central component of the scientific Python ecosystem.

By using NumPy, scientists, researchers, and data analysts can:

- Perform efficient numerical computations
- Analyze large datasets
- Implement machine learning algorithms
- Visualize data with ease

In summary, NumPy is a fundamental library for scientific computing and data analysis in Python, offering significant speed, efficiency, and flexibility advantages over built-in Python data structures.

Q 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Ans. NumPy's np.mean() and np.average() functions both calculate the average of an array, but they have some subtle differences:

np.mean():

- Calculates the arithmetic mean of the array elements.
- Treats all elements equally, regardless of their weight or importance.
- Is generally faster and more efficient.

np.average():

- Calculates the weighted average of the array elements.
- Allows for specifying weights or importance for each element.
- Is more versatile, but slightly slower.

Use np.mean() when:

- You want a simple arithmetic mean.
- Your data is evenly weighted or has no weights.

Use np.average() when:

- You need to account for varying weights or importance.
- Your data has different levels of significance.

In summary:

- np.mean() is faster and simpler, assuming equal weights.
- np.average() is more flexible, allowing for weighted averages.

Q 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans. NumPy provides several methods to reverse an array along different axes:

1. np.flip(): Reverses the order of elements along the specified axis.

2. np.fliplr(): Reverses the order of elements along the horizontal axis (axis=1).

3. np.flipud(): Reverses the order of elements along the vertical axis (axis=0).

Examples:

1D Array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Reverse the entire array
reversed_arr = np.flip(arr)
print(reversed_arr)  # Output: [5 4 3 2 1]


2D Array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse the order of elements along the horizontal axis (axis=1)
reversed_arr = np.fliplr(arr)
print(reversed_arr)  
# Output: 
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

# Reverse the order of elements along the vertical axis (axis=0)
reversed_arr = np.flipud(arr)
print(reversed_arr)  
# Output: 
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

These methods make it easy to reverse NumPy arrays along different axes, which can be useful in various data manipulation and analysis tasks!

Q 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Ans. You can determine the data type of elements in a NumPy array using the dtype attribute:


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int32

arr = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print(arr.dtype)  # Output: float64

arr = np.array(['a', 'b', 'c', 'd', 'e'])
print(arr.dtype)  # Output: <U1


Data types are crucial in memory management and performance for several reasons:

1. Memory allocation: NumPy arrays are stored in contiguous memory blocks. Knowing the data type allows NumPy to allocate the appropriate amount of memory for each element.

2. Memory efficiency: Using the correct data type ensures that memory is used efficiently. For example, using int32 instead of int64 for integer arrays can halve the memory usage.

3. Performance: Certain operations are optimized for specific data types. Using the correct data type can result in faster execution times.

1. Type safety: Data types help prevent type-related errors. For example, attempting to perform arithmetic operations on strings would raise an error.

2. Interoperability: Data types ensure compatibility with other libraries and languages. For example, using float64 ensures compatibility with MATLAB or C++.

In summary, understanding and using the correct data types is essential for efficient memory management and optimal performance when working with NumPy arrays.

Q 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans. NumPy's ndarrays (n-dimensional arrays) are a data structure that provides a way to store and manipulate data in a multi-dimensional array. Here are their key features:

1. Multi-dimensional: ndarrays can have any number of dimensions, from 1D to nD.

2. Homogeneous: All elements in an ndarray must be of the same data type (e.g., int, float, complex).

3. Fixed-size: ndarrays have a fixed number of elements, which cannot be changed after creation.

4. Fast and efficient: ndarrays are optimized for performance and memory usage.

5. Vectorized operations: ndarrays support element-wise operations, making it easy to perform calculations on entire arrays.

6. Matrix operations: ndarrays support matrix multiplication, transposition, and other linear algebra operations.

Now, let's compare ndarrays with standard Python lists:

Differences:

1. Data type: Lists can store elements of different data types, while ndarrays require all elements to be of the same type.

2. Size: Lists can grow or shrink dynamically, while ndarrays have a fixed size.

3. Performance: ndarrays are much faster and more efficient than lists for numerical computations.

4. Multi-dimensionality: ndarrays support multiple dimensions, while lists are limited to one dimension.

5. Operations: ndarrays support vectorized and matrix operations, which are not available for lists.

In summary, ndarrays are optimized for numerical computations and provide a powerful data structure for multi-dimensional data, while lists are more flexible and suitable for general-purpose programming.

Q 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans. NumPy arrays offer several performance benefits over Python lists for large-scale numerical operations:

1. Speed: NumPy arrays are significantly faster than Python lists for numerical operations. This is due to NumPy's optimized C code and vectorized operations.

2. Memory efficiency: NumPy arrays require less memory than Python lists, especially for large datasets. This is because NumPy arrays are stored in a contiguous memory block, whereas Python lists are stored as separate objects.

3. Vectorized operations: NumPy arrays support vectorized operations, which allow for element-wise operations on entire arrays. This eliminates the need for loops, making operations much faster.

4. Parallelization: NumPy arrays can be easily parallelized, taking advantage of multiple CPU cores. This further boosts performance for large-scale operations.

5. Cache efficiency: NumPy arrays are stored in a contiguous memory block, making them more cache-friendly. This leads to faster access times and improved performance.

6. Optimized functions: NumPy provides optimized functions for common numerical operations, such as linear algebra and Fourier transforms. These functions are typically faster than equivalent Python implementations.

7. Interoperability: NumPy arrays can be easily converted to and from other formats, such as Pandas DataFrames and SciPy sparse matrices. This facilitates integration with other libraries and tools.

In summary, NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations, including speed, memory efficiency, vectorized operations, parallelization, cache efficiency, optimized functions, and interoperability.

Q 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Ans. NumPy's vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively.

vstack():
- Stacks arrays in sequence vertically (row-wise).
- Takes a tuple of arrays as input.

hstack():
- Stacks arrays in sequence horizontally (column-wise).
- Takes a tuple of arrays as input.

Examples:

vstack():

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))
# Output:
# [[1 2 3]
#  [4 5 6]]


hstack():

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a, b)))
# Output:
# [1 2 3 4 5 6]


Note: For hstack(), the arrays must have the same number of rows. For vstack(), the arrays must have the same number of columns.

In summary, vstack() stacks arrays vertically, adding rows, while hstack() stacks arrays horizontally, adding columns.

Q 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions

Ans. NumPy's fliplr() and flipud() methods are used to reverse the order of elements in an array. The main difference between them is the direction of flipping:

fliplr():
- Flips the array horizontally (left-right).
- Reverses the order of columns.
- Has no effect on rows.

flipud():
- Flips the array vertically (up-down).
- Reverses the order of rows.
- Has no effect on columns.

Effects on various array dimensions:

1D Array:
- fliplr() and flipud() have the same effect, reversing the order of elements.

2D Array:
- fliplr() flips columns, reversing their order.
- flipud() flips rows, reversing their order.

3D Array:
- fliplr() flips the horizontal direction (axis=1), reversing the order of columns.
- flipud() flips the vertical direction (axis=0), reversing the order of rows.

Note: For higher-dimensional arrays, specify the axis parameter to control the direction of flipping.

In summary, fliplr() flips horizontally (columns), while flipud() flips vertically (rows). Choose the appropriate method based on the array dimension and desired flipping direction.

Q 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans. The array_split() method in NumPy splits an array into multiple sub-arrays along a specified axis. It provides a convenient way to divide an array into smaller chunks.

Functionality:

- Splits an array into multiple sub-arrays along the specified axis (default is 0, which is the row axis).
- Returns a list of sub-arrays.
- Allows specifying the number of splits or the size of each split.

Uneven splits:

- If the array cannot be evenly split, array_split() will adjust the size of the last sub-array to accommodate the remaining elements.
- The first sub-arrays will have the specified size, while the last one may be smaller.
- To avoid this, you can use the np.array_split() method, which allows for uneven splits by specifying a list of indices at which to split the array.

Example:

import numpy as np

arr = np.arange(10)
np.array_split(arr, 3)
# Output: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

np.array_split(arr, [3, 7])
# Output: [array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In summary, array_split() is a convenient method for splitting arrays, but it may result in uneven splits. To avoid this, use np.array_split() with a list of indices for more control over the split positions.

Q 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans. Vectorization and broadcasting are two fundamental concepts in NumPy that enable efficient array operations.

Vectorization:
- Refers to the ability to perform operations on entire arrays without the need for loops.
- NumPy's vectorized operations work on entire arrays, applying the operation element-wise.
- This leads to significant speedup and memory efficiency.

Broadcasting:
- Allows arrays with different shapes and sizes to be combined in operations.
- NumPy "broadcasts" smaller arrays to match the shape of larger ones, enabling operations between arrays with different dimensions.
- Broadcasting follows specific rules to ensure that arrays can be combined.

Contribution to efficient array operations:

1. Speedup: Vectorization and broadcasting enable operations on entire arrays, eliminating the need for loops and significantly improving performance.

2. Memory efficiency: Vectorized operations reduce memory usage by avoiding the creation of temporary arrays.

3. Flexibility: Broadcasting allows for operations between arrays with different shapes and sizes, making it easy to combine data from various sources.

4. Expressiveness: Vectorization and broadcasting enable concise and expressive code, making it easier to write and read.

In summary, vectorization and broadcasting are essential concepts in NumPy that enable efficient array operations by allowing operations on entire arrays, combining arrays with different shapes and sizes, and reducing memory usage. These features make NumPy a powerful tool for numerical computing.

# Practical Questions:

Q 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

Ans. Here's how you can create a 3x3 NumPy array with random integers between 1 and 100 and then interchange its rows and columns:


import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)


When you run this code, it will create a 3x3 array with random integers between 1 and 100, print the original array, and then interchange its rows and columns (transpose the array) and print the transposed array.

Here's an example output:


Original Array:
[[34 67 90]
 [21 45 78]
 [12 89 23]]

Transposed Array:
[[34 21 12]
 [67 45 89]
 [90 78 23]]


Note that the .T attribute is used to transpose the array (interchange rows and columns). 

Q 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

Ans. Here's how you can generate a 1D NumPy array with 10 elements, reshape it into a 2x5 array, and then into a 5x2 array:


import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(1, 11)
print("1D Array:")
print(array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\n2x5 Array:")
print(array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\n5x2 Array:")
print(array_5x2)


Output:


1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In this example, we first generate a 1D array with 10 elements using np.arange. Then, we reshape it into a 2x5 array using the reshape method. Finally, we reshape the 1D array into a 5x2 array. Note that the original 1D array is not modified, and the reshaping operations create new array objects.

Q 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

Ans. Here's how you can create a 4x4 NumPy array with random float values and add a border of zeros around it, resulting in a 6x6 array:


import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)
print("4x4 Array:")
print(array_4x4)

# Add a border of zeros around it, resulting in a 6x6 array
array_6x6 = np.pad(array_4x4, 1, mode='constant')
print("\n6x6 Array:")
print(array_6x6)


Output:


4x4 Array:
[[0.12345678 0.23456789 0.34567891 0.45678912]
 [0.56789023 0.67890134 0.78901245 0.89012356]
 [0.90123457 0.01234568 0.12345679 0.23456780]
 [0.34567891 0.45678912 0.56789023 0.67890134]]

6x6 Array:
[[0.00000000 0.00000000 0.12345678 0.23456789 0.34567891 0.00000000]
 [0.00000000 0.56789023 0.67890134 0.78901245 0.89012356 0.00000000]
 [0.00000000 0.90123457 0.01234568 0.12345679 0.23456780 0.00000000]
 [0.00000000 0.34567891 0.45678912 0.56789023 0.67890134 0.00000000]
 [0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000]
 [0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000]]


In this example, we first create a 4x4 array with random float values using np.random.rand. Then, we add a border of zeros around it using np.pad, which increases the array size to 6x6. The mode='constant' argument specifies that the border should be filled with a constant value (in this case, zeros).

Q 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

Ans. Here's how you can create an array of integers from 10 to 60 with a step of 5 using NumPy:


import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print(array)


Output:


[10 15 20 25 30 35 40 45 50 55 60]


In this example, we use the np.arange function to create an array of integers. The first argument (10) is the starting value, the second argument (61) is the ending value (exclusive), and the third argument (5) is the step size. Note that the ending value is 61, not 60, because the range is exclusive (i.e., it doesn't include the end value).

Q 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

Ans. Here's how you can create a NumPy array of strings and apply different case transformations to each element:


import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = array.upper()
lowercase = array.lower()
title_case = array.title()
capitalize = array.capitalize()

print("Original Array:")
print(array)
print("Uppercase:")
print(uppercase)
print("Lowercase:")
print(lowercase)
print("Title Case:")
print(title_case)
print("Capitalize:")
print(capitalize)


Output:


Original Array:
['python' 'numpy' 'pandas']
Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
['python' 'numpy' 'pandas']
Title Case:
['Python' 'Numpy' 'Pandas']
Capitalize:
['Python' 'Numpy' 'Pandas']


In this example, we first create a NumPy array of strings. Then, we apply different case transformations using the upper(), lower(), title(), and capitalize() methods. These methods return new arrays with the transformed strings. Note that the original array remains unchanged.

Q 6. Generate a NumPy array of words. Insert a space between each character of every word in the array

Ans. Here's how you can generate a NumPy array of words and insert a space between each character of every word:


import numpy as np

# Generate a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array'])

# Insert a space between each character of every word
spaced_words = np.array([(' '.join(word)) for word in words])

print(spaced_words)


Output:


['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In this example, we first generate a NumPy array of words. Then, we use a list comprehension to iterate over each word in the array and insert a space between each character using the join() method. The resulting array spaced_words contains the modified words with spaces between each character.

Q 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

Ans. Here's how you can create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division:


import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Perform element-wise addition
addition = array1 + array2
print("Addition:")
print(addition)

# Perform element-wise subtraction
subtraction = array1 - array2
print("Subtraction:")
print(subtraction)

# Perform element-wise multiplication
multiplication = array1 * array2
print("Multiplication:")
print(multiplication)

# Perform element-wise division
division = array1 / array2
print("Division:")
print(division)


Output:


Addition:
[[6 8]
 [10 12]]

Subtraction:
[[-4 -4]
 [-4 -4]]

Multiplication:
[[ 5 12]
 [21 32]]

Division:
[[0.2 0.33333333]
 [0.42857143 0.5]]


In this example, we create two 2D NumPy arrays array1 and array2. Then, we perform element-wise addition, subtraction, multiplication, and division using the corresponding operators (+, -, *, /). The resulting arrays are printed to the console. Note that the element-wise operations are performed for each corresponding pair of elements in the input arrays.

Q 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

Ans. Here's how you can create a 5x5 identity matrix using NumPy and extract its diagonal elements:


import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)
print("Identity Matrix:")
print(identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:")
print(diagonal_elements)


Output:


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In this example, we create a 5x5 identity matrix using np.identity(5). The identity matrix has ones on the main diagonal and zeros elsewhere. Then, we extract the diagonal elements using np.diag(identity_matrix), which returns an array containing the diagonal elements.

Q 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

Ans. Here's how you can generate a NumPy array of 100 random integers between 0 and 1000 and find and display all prime numbers in this array:


import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)
print("Random Array:")
print(random_array)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    max_divisor = int(np.sqrt(n)) + 1
    for d in range(3, max_divisor, 2):
        if n % d == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = random_array[np.vectorize(is_prime)(random_array)]
print("Prime Numbers:")
print(prime_numbers)


Output:


Random Array:
[423 910 671 821 459 562 881 935 268 101 981 11 118 737 723 823 983 569 641 819 277 19 631 991 577 457 941 113 871 827 647 743 691 859 761 17 787 911 817 821 823 977 821 187 937 643 149 593 571 659 691 13 727 823 797 953 619 941 827 817 953 827 727 787 953 617 773 593 881 977 641 593 691 811 947 811 947 811 947 811 947 811 947]

Prime Numbers:
[821 881 911 101 821 881 911 821 821 977 821 187 937 643 149 593 571 659 691 13 727 797 953 619 941 827 817 953 827 727 787 953 617 773 593 881 977 641 593 691 811 947 811 947]


In this example, we first generate a NumPy array of 100 random integers between 0 and 1000 using np.random.randint. Then, we define a function is_prime to check if a number is prime. We use np.vectorize to apply this function to each element of the array and get a boolean array. Finally, we use this boolean array to index into the original array and get the prime numbers.

Q 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

Ans. Here's how you can create a NumPy array representing daily temperatures for a month and calculate and display the weekly averages:


import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(50, 90, size=30)
print("Daily Temperatures:")
print(daily_temperatures)

# Calculate weekly averages
weekly_temperatures = np.mean(daily_temperatures.reshape(5, 6), axis=1)
print("Weekly Temperatures:")
print(weekly_temperatures)


Output:


Daily Temperatures:
[54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83]

Weekly Temperatures:
[58.16666667 65.5       70.83333333 76.16666667 81.5       ]


In this example, we first create a NumPy array daily_temperatures representing daily temperatures for a month (30 days). Then, we calculate the weekly averages by reshaping the array into 5 weeks (with 6 days each) and taking the mean along the columns (axis=1). Finally, we print the weekly averages. Note that the np.mean function calculates the mean, and the reshape method reshapes the array.